db_file = "database.vdb"
db_file_data = "data"
MAIN = "MAIN"
CAESAR = "CAESAR"

# CAESAR
# ---------------------------------------------------

CAESAR_FILE_ENCRYPT = "CAESAR_FILE_ENCRYPT"
CAESAR_FILE_DECRYPT = "CAESAR_FILE_DECRYPT"
CAESAR_FILE_ET = "CAESAR_FILE_ET"
CAESAR_FILE_DT = "CAESAR_FILE_DT"

CAESAR_SHIFT_ENCRYPT = "CAESAR_SHIFT_ENCRYPT"
CAESAR_SHIFT_DECRYPT = "CAESAR_SHIFT_DECRYPT"
CAESAR_SHIFT_ET = "CAESAR_SHIFT_ET"
CAESAR_SHIFT_DT = "CAESAR_SHIFT_DT"

CAESAR_LANG_ET = "CAESAR_SHIFT_ET"
CAESAR_LANG_DT = "CAESAR_SHIFT_DT"

# CAESAR
# --------------------------------------------------------
