db_file = "database.vdb"
MAIN = "MAIN"
CAESAR = "CAESAR"

# CAESAR
# ---------------------------------------------------

CAESAR_FILE_ENCRYPT = "CAESAR_FILE_ENCRYPT"
CAESAR_FILE_DECRYPT = "CAESAR_FILE_DECRYPT"
CAESAR_FILE_ET = "CAESAR_FILE_ET"
CAESAR_FILE_DT = "CAESAR_FILE_DT"
CAESAR_FILE_DWS = "CAESAR_FILE_DWS"
CAESAR_FILE_DTWS = "CAESAR_FILE_DTWS"

CAESAR_SHIFT_ENCRYPT = "CAESAR_SHIFT_ENCRYPT"
CAESAR_SHIFT_DECRYPT = "CAESAR_SHIFT_DECRYPT"
CAESAR_SHIFT_ET = "CAESAR_SHIFT_ET"
CAESAR_SHIFT_DT = "CAESAR_SHIFT_DT"

CAESAR_LANG_ET = "CAESAR_SHIFT_ET"
CAESAR_LANG_DT = "CAESAR_SHIFT_DT"
CAESAR_LANG_DTWS = "CAESAR_LANG_DTWS"

# CAESAR
# --------------------------------------------------------
